package com.couriertracker;
import android.app.*;import android.content.*;import android.location.*;import android.os.*;import org.json.*;
public class TrackingService extends Service implements LocationListener{
 LocationManager lm;SharedPreferences p;long start,elapsed,lastPoint;double distance,lastLat,lastLon;boolean paused,hasLast;JSONArray points=new JSONArray();
 public void onCreate(){super.onCreate();p=getSharedPreferences("track",0);}
 void save(){try{JSONObject o=new JSONObject();o.put("start",start);o.put("elapsed",elapsed);o.put("distance",distance);o.put("paused",paused);o.put("lat",lastLat);o.put("lng",lastLon);o.put("points",points.toString());p.edit().putString("state",o.toString()).apply();}catch(Exception e){}}
 public int onStartCommand(Intent i,int f,int id){String a=i.getAction();if("START".equals(a)){start=System.currentTimeMillis();elapsed=0;distance=0;paused=false;hasLast=false;points=new JSONArray();save();foreground();request();}else if("PAUSE".equals(a)){elapsed=System.currentTimeMillis()-start;paused=true;save();}else if("RESUME".equals(a)){start=System.currentTimeMillis()-elapsed;paused=false;save();request();}else if("STOP".equals(a)){elapsed=System.currentTimeMillis()-start;save();stopLocation();stopForeground(true);stopSelf();}return START_STICKY;}
 void foreground(){if(Build.VERSION.SDK_INT>=26){NotificationChannel n=new NotificationChannel("tracking","GPS tracking",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(n);}Notification n=new Notification.Builder(this,"tracking").setContentTitle("Courier Tracker").setContentText("Shift is being tracked").setSmallIcon(android.R.drawable.ic_menu_mylocation).setOngoing(true).build();startForeground(7,n);}
 void request(){if(lm==null)lm=(LocationManager)getSystemService(LOCATION_SERVICE);try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,5000,8,this,Looper.getMainLooper());}catch(SecurityException e){}}
 void stopLocation(){if(lm!=null)try{lm.removeUpdates(this);}catch(Exception e){}}
 public void onLocationChanged(Location l){if(paused)return;long now=System.currentTimeMillis();if(hasLast){float[] r=new float[1];Location.distanceBetween(lastLat,lastLon,l.getLatitude(),l.getLongitude(),r);if(r[0]>=2&&r[0]<=150)distance+=r[0]/1000.0;}lastLat=l.getLatitude();lastLon=l.getLongitude();hasLast=true;if(now-lastPoint>8000){try{JSONObject o=new JSONObject();o.put("lat",lastLat);o.put("lng",lastLon);o.put("t",now);points.put(o);}catch(Exception e){}lastPoint=now;}elapsed=now-start;save();}
 public void onProviderEnabled(String s){}public void onProviderDisabled(String s){}public void onStatusChanged(String s,int st,Bundle b){}public void onDestroy(){stopLocation();super.onDestroy();}public IBinder onBind(Intent i){return null;}
}
