package com.couriertracker;
import android.app.*;import android.content.*;import android.location.*;import android.os.*;import org.json.*;
public class TrackingService extends Service implements LocationListener{
 LocationManager lm;SharedPreferences p;long start,elapsed,lastPoint;double distance,lastLat,lastLon,lastSpeed,lastAccuracy,lastAltitude;boolean paused,hasLast;JSONArray points=new JSONArray();
 @Override public void onCreate(){super.onCreate();p=getSharedPreferences("track",0);load();}
 void load(){try{JSONObject o=new JSONObject(p.getString("state","{}"));start=o.optLong("start",0);elapsed=o.optLong("elapsed",0);distance=o.optDouble("distance",0);paused=o.optBoolean("paused",false);lastLat=o.optDouble("lat",0);lastLon=o.optDouble("lng",0);lastSpeed=o.optDouble("speed",0);lastAccuracy=o.optDouble("accuracy",0);lastAltitude=o.optDouble("altitude",0);points=new JSONArray(o.optString("points","[]"));hasLast=start>0;}catch(Exception e){points=new JSONArray();}}
 void save(){try{JSONObject o=new JSONObject();o.put("start",start);o.put("elapsed",elapsed);o.put("distance",distance);o.put("paused",paused);o.put("lat",lastLat);o.put("lng",lastLon);o.put("speed",lastSpeed);o.put("accuracy",lastAccuracy);o.put("altitude",lastAltitude);o.put("points",points.toString());p.edit().putString("state",o.toString()).apply();}catch(Exception e){}}
 @Override public int onStartCommand(Intent i,int f,int id){String a=i==null?null:i.getAction();if("START".equals(a)){start=System.currentTimeMillis();elapsed=0;distance=0;paused=false;hasLast=false;lastPoint=0;points=new JSONArray();save();foreground();request();}else if("PAUSE".equals(a)){if(start>0)elapsed=System.currentTimeMillis()-start;paused=true;save();}else if("RESUME".equals(a)){start=System.currentTimeMillis()-elapsed;paused=false;save();foreground();request();}else if("STOP".equals(a)){if(start>0&&!paused)elapsed=System.currentTimeMillis()-start;stopLocation();p.edit().remove("state").apply();start=0;elapsed=0;distance=0;paused=false;points=new JSONArray();stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();}return START_STICKY;}
 void foreground(){if(Build.VERSION.SDK_INT>=26){NotificationChannel n=new NotificationChannel("tracking","GPS tracking",NotificationManager.IMPORTANCE_LOW);n.setDescription("Active courier shift GPS");getSystemService(NotificationManager.class).createNotificationChannel(n);}Notification n=new Notification.Builder(this,"tracking").setContentTitle("Courier Tracker").setContentText("GPS tracking is active").setSmallIcon(android.R.drawable.ic_menu_mylocation).setOngoing(true).build();startForeground(7,n);}
 void request(){if(lm==null)lm=(LocationManager)getSystemService(LOCATION_SERVICE);try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,4000,5,this,Looper.getMainLooper());}catch(SecurityException e){}}
 void stopLocation(){if(lm!=null)try{lm.removeUpdates(this);}catch(Exception e){}}
 @Override public void onLocationChanged(Location l){if(paused)return;long now=System.currentTimeMillis();if(hasLast){float[] r=new float[1];Location.distanceBetween(lastLat,lastLon,l.getLatitude(),l.getLongitude(),r);if(r[0]>=2&&r[0]<=200)distance+=r[0]/1000.0;}lastLat=l.getLatitude();lastLon=l.getLongitude();lastSpeed=l.hasSpeed()?l.getSpeed()*3.6:0;lastAccuracy=l.hasAccuracy()?l.getAccuracy():0;lastAltitude=l.hasAltitude()?l.getAltitude():0;hasLast=true;if(now-lastPoint>8000){try{JSONObject o=new JSONObject();o.put("lat",lastLat);o.put("lng",lastLon);o.put("t",now);o.put("speed",lastSpeed);points.put(o);}catch(Exception e){}lastPoint=now;}elapsed=now-start;save();}
 @Override public void onProviderEnabled(String s){}@Override public void onProviderDisabled(String s){}@Override public void onStatusChanged(String s,int st,Bundle b){}@Override public void onDestroy(){stopLocation();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}